# Permalinks
permalink:            pretty

# Setup
title:                'Kathrin & Lukas'
description:          'gheirat wird!'
baseurl:              /

author:
  name:               'Kathi & Lukas'
  url:
